backend:
  name: github
  repo: jgirls-lab/Jgirls
  branch: main
  base_url: https://eoko2t9bgaec6yk.m.pipedream.net

media_folder: "images"
public_folder: "/images"

collections:
  - name: "gallery"
    label: "ギャラリー"
    folder: "content"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "画像", name: "image", widget: "image" }
      - { label: "タグ", name: "tags", widget: "list" }
