backend:
  name: github
  repo: お兄ちゃんのユーザー名/リポジトリ名
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "gallery"
    label: "ギャラリー"
    folder: "content"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "画像", name: "image", widget: "image" }
      - { label: "タグ", name: "tags", widget: "list" }
